version: '3.8'

services:
  my-mongodb:
    image: mongo:latest
    container_name: my-mongodb
    volumes:
      - mongodbdata:/data/db
    networks:
      - my-network

  node-app:
    image: snowman12320/docker-express-sample-mongo
    container_name: node-app
    ports:
      - '80:3000'
    environment:
      MONGODB_URL: ${COMPOSE_DB_URL}

    depends_on:
      - my-mongodb
    networks:
      - my-network
    volumes:
      # 將應用資料映射到容器內 (前本地資料夾位置 或 雲主機路徑如：/root/docker-express-sample-mongo ，後 容器內的檔案路徑)
      - /Users/william/Documents/docker-express-sample-mongo:/usr/local/app/dist

volumes:
  mongodbdata:

networks:
  my-network:
    driver: bridge
