version: '3.8'

services:
  my-mongodb:
    image: mongo:latest
    container_name: my-mongodb
    volumes:
      - mongodbdata:/data/db
    networks:
      - my-network

  node-app:
    image: snowman12320/docker-express-sample-mongo
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: ${COMPOSE_DB_URL}
      # - MONGODB_URL=mongodb://my-mongodb/mydatabase
    depends_on:
      - my-mongodb
    networks:
      - my-network
    volumes:
      # 將應用資料映射到容器內
      - /root/docker-express-sample-mongo:/usr/local/app/dist  


volumes:
 # 不能mongodbdata:{}
 mongodbdata: 

networks:
  my-network:
    driver: bridge
